import './globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="aqua">
      <body className="min-h-screen bg-white flex justify-center align-middle">{children}</body>
    </html>
  )
}
